# Generated by Django 4.2.18 on 2025-02-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.DateField(),
        ),
    ]
