# Generated by Django 4.2.18 on 2025-02-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimsapp', '0002_alter_timelineevent_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelineevent',
            old_name='year',
            new_name='event_year',
        ),
    ]
