# Generated by Django 4.2.18 on 2025-02-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimsapp', '0003_rename_year_timelineevent_event_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelineevent',
            old_name='event_year',
            new_name='event_date',
        ),
    ]
