# Generated by Django 4.2.18 on 2025-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimsapp', '0005_pilgrimboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrimboard',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
