# Generated by Django 4.2.18 on 2025-06-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimsapp', '0007_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('general', '일반'), ('tech', '창조'), ('account', '구원'), ('other', '재림')], default='general', max_length=20, verbose_name='카테고리'),
        ),
    ]
