# Generated by Django 4.2.18 on 2025-02-05 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
