# Generated by Django 4.2.18 on 2025-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0002_note_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='intpilgrim/')),
                ('description', models.TextField()),
            ],
        ),
    ]
