# Generated by Django 4.2.18 on 2025-02-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0003_specialpilgrim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilgrimageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='specialpilgrim',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wayapp.pilgrimagegroup'),
        ),
    ]
