# Generated by Django 4.2.18 on 2025-02-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0004_pilgrimagegroup_specialpilgrim_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialpilgrim',
            name='group',
        ),
        migrations.DeleteModel(
            name='PilgrimageGroup',
        ),
        migrations.DeleteModel(
            name='SpecialPilgrim',
        ),
    ]
