# Generated by Django 4.2.18 on 2025-02-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wayapp', '0005_remove_specialpilgrim_group_delete_pilgrimagegroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='intpilgrim/')),
                ('description', models.TextField()),
                ('group', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
