# Generated by Django 4.2.18 on 2025-02-21 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0006_specialpilgrim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialpilgrim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specialpilgrim',
            name='image',
        ),
        migrations.AddField(
            model_name='specialpilgrim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PilgrimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sppilgrim/')),
                ('special_pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spimages', to='wayapp.specialpilgrim')),
            ],
        ),
        migrations.CreateModel(
            name='PilgrimDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('special_pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdescriptions', to='wayapp.specialpilgrim')),
            ],
        ),
    ]
