# Generated by Django 4.2.18 on 2025-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0008_pilgrimvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrimvideo',
            name='video',
            field=models.FileField(upload_to='pilvideos/'),
        ),
    ]
