# Generated by Django 4.2.18 on 2025-02-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bethel',
        ),
    ]
