# Generated by Django 4.2.18 on 2025-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
