# Generated by Django 4.2.18 on 2025-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_medfirst',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img_med/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_medsecond',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img_med/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_medthird',
            field=models.FileField(blank=True, null=True, upload_to='profile_video_med/'),
        ),
    ]
