# Generated by Django 4.2.18 on 2025-06-06 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitingBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='recite_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_meditation', models.CharField(choices=[('none', '첨부 안함'), ('med_first', '묵상 이미지 1'), ('med_second', '묵상 이미지 2'), ('med_video', '묵상 영상')], default='none', help_text='프로필의 묵상 파일 중 첨부할 파일을 선택하세요', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
